<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2021/03/22 15:58:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=jobeetdb;dbname=jobeet',
  'username' => 'root',
  'password' => 'root',
  'name' => 'doctrine',
)),);
