version: '2'
services:
  jobeetdb:
    image: mysql:5.7
    ports:
     - 3306:3306
    volumes:
     - ./mysql-data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: "root"
     MYSQL_DATABASE: "jobeet"

  jobeet:
    build:
      context: .
      dockerfile: Dockerfile
    image: php54-docker
    container_name: test
    ports:
      - 8080:8080
      - 80:80
    links:
      - jobeetdb:jobeetdb
    volumes:
      - ./.confFigaro/jobeet.conf:/etc/httpd/conf.d/jobeet.conf
      - ./.confFigaro/php.ini:/etc/php.ini
      - ./codigo/:/var/www/html
    working_dir: /var/www/html/
    stdin_open: true
    tty: true
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - jobeetdb:jobeetdb
    environment:
     PMA_HOST: jobeetdb
     PMA_PORT: 3306
    ports:
     - 8081:80
